### ISSUE TITLE
Anonymous events

### ISSUE THREAD

**Issue by emeve89** [customerio/customerio-ruby#25]
Hi,

I tried to create and send some "anonymous events" (after checking the gem code, of course) and I found out that they are useless (I hope not), because the event data won't show up in the customer.io interface.

So, should this method be removed from the gem?

Cheers.

**Comment by samkpower** [comment]
+1 I think [this line](https://github.com/customerio/customerio-ruby/blob/master/lib/customerio/client.rb#L28) needs to be fixed for anonymous events to work - it doesn't account for passing both an event name and an attributes hash.

**Comment by alisdair** [comment]
Anonymous events don't show up in our event logs, but they can be used to trigger campaigns. [See our documentation on sending emails to people who don't exist in Customer.io](https://customer.io/docs/invitation-emails.html).
