### ISSUE TITLE
Only working with json: true on Initialize

### ISSUE THREAD

**Issue by ADStrovers** [customerio/customerio-ruby#27]
I'm not sure if this is happening to anyone else but I was having an issue getting the gem to post information to Customer.io without sending it as json.  Here is the code that was running.

```ruby
CUSTOMERIO = Customerio::Client.new(
  Rails.configuration.customerio[:site_id], 
  Rails.configuration.customerio[:api_secret])
```

Upon a user signing up I had this for sending code:

```ruby
if @team.org.org_type.id == 1
  setup = @team.is_setup?
  CUSTOMERIO.identify(
    id: @team.id,
    email: @user.email,
    created_at: @user.created_at,
    first_name: @user.first_name,
    last_name: @user.last_name,
    team_cars: @team.list_cars,
    plan: @plan.name,
    is_setup: setup
  )
end
```

However, when it was run on staging it would not work unless we added some type of breakpoint after the .identify() call such as a binding.pry or a puts to the console.

I am not quite sure what was going on but the fix I found was just giving the initialize json: true option.

Has anyone else run into this issue?  If so, is there another way to fix this?

**Comment by jrallison** [comment]
Hey Andrew,

Can you help me understand the issue? What do you mean when you say it's not working? Are you getting an error? Which error?

What the raw data are you sending into identify? It'd be helpful so we can reproduce the issue.

By default, we use form encoding for the data sent over the wire to the API, setting `json: true` serializes the data using JSON instead.

I'm guessing `@team.list_cars` may be an array or array of hashes. Arrays of hashes can have ambiguous meaning when serialized through form encoding.

**Comment by ADStrovers** [comment]
That might actually have been the issue.  list_cars returns an array of Ruby objects.  

Browsing the logs returned no errors that I saw but the code was executing just fine.  It just wasn't being updated on the customerio.io site.  Without changing anything about it, inserting in some type of break after the .identify call made it update on customer.io and I could not figure out why.  However, taking out that break and serializing the data using JSON seems to have fixed the issue regardless.

I hope that is enough information.  I feel like I just repeated what I already told you but maybe it was due to then array of objects?

**Comment by jrallison** [comment]
Ah, so if the values are ruby objects (not an array or a hash), that may be the different. JSON serialization will be sure to generate valid JSON, we we accept.

Again, for us to help, we'd need to know the actual data and ruby objects you're attempting to send.

Without setting `json: true`, we're passing the data you're sending to `identify` straight into the body of an instance of `Net::HTTP::Put`.

Perhaps there's an issue serializing the data you're attempting to send into form-encoded values inside `Net::HTTP`? Some additional info: http://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html

**Comment by ADStrovers** [comment]
Sorry for the late response!  It was indeed an issue with trying to send a ruby object through Net::HTTP.  After writing a method to convert it to a hash it works perfectly fine.  

Thank you for the walk through @jrallison.  I appreciate the patience and help!
