### ISSUE TITLE
Remove httparty dependency

### ISSUE THREAD

**Issue by jrallison** [customerio/customerio-ruby#3]
Can cause bundle nightmares.  We don't really need it.

**Comment by mbasset** [comment]
The httparty dependency bump down to 0.12 or earlier to support 1.8.7 is causing issues for us right now. This is also a strange change as 1.8.7 is deprecated by the ruby team 2 years ago https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/
