### ISSUE TITLE
Customerio::Client::InvalidResponse error does not display message

### ISSUE THREAD

**Issue by kjleitz** [customerio/customerio-ruby#50]
If a `Customerio::Client::InvalidResponse` error is raised (e.g., in `Customerio::Client#verify_response` at `lib/customerio/client.rb:146` on the `master` branch, or at `lib/customerio/client.rb:95` in `v1.0.0`), it does not show the error message associated with the exception:

```
2.3.3 :001 > raise Customerio::Client::InvalidResponse.new("this is the message", "this is the response data")
Customerio::Client::InvalidResponse: Customerio::Client::InvalidResponse
	from (irb):1
	from /Users/keegan/.rvm/gems/ruby-2.3.3@openbay/gems/railties-4.2.7/lib/rails/commands/console.rb:110:in `start'
	from /Users/keegan/.rvm/gems/ruby-2.3.3@openbay/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
	from /Users/keegan/.rvm/gems/ruby-2.3.3@openbay/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
	[...]
```

...whereas you would expect the message to be in the output, like this:

```
2.3.3 :002 > raise Customerio::Client::InvalidResponse.new("this is the message", "this is the response data")
Customerio::Client::InvalidResponse: this is the message
	from (irb):2
	from /Users/keegan/.rvm/gems/ruby-2.3.3@openbay/gems/railties-4.2.7/lib/rails/commands/console.rb:110:in `start'
	from /Users/keegan/.rvm/gems/ruby-2.3.3@openbay/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
	from /Users/keegan/.rvm/gems/ruby-2.3.3@openbay/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
	[...]
```

Since it doesn't, there's no way to see the response payload or the HTTP error code, expected here:

```ruby
# lib/customerio/client.rb

# ...

    def verify_response(response)
      if response.code.to_i >= 200 && response.code.to_i < 300
        response
      else
        raise InvalidResponse.new("Customer.io API returned an invalid response: #{response.code}", response)
      end
    end

# ...
```

**Comment by hussainakram** [comment]
It could be the issue with your credentials otherwise it should work perfectly. I had the same problem but it was solved by setting credentials correctly.

**Comment by kjleitz** [comment]
@hussainakram The issue isn't for the error itself, but with how the error is displayed. There's a bug here where the error message itself is not present in the exception output because of how the custom error class `InvalidResponse` is initialized. I made a PR for the fix a while ago here: https://github.com/customerio/customerio-ruby/pull/51
