### ISSUE TITLE
How to track page view events?

### ISSUE THREAD

**Issue by pauljacksonrodgers** [customerio/customerio-ruby#92]
I see methods like `trackPageView` in the Python SDK, but not in this Ruby SDK. Based on the suggestion [here](https://github.com/customerio/customerio-ruby/pull/32), I tried sending the page view events like

```ruby
client.track(15, 'page', path: '/whatever')
```

but those just appear as "regular" events in the activity log, not actually events of type `pageView`. How can I use this SDK to send events that will actually come through to the dashboard as page views?

**Comment by hownowstephen** [comment]
following up here @pauljacksonrodgers you should be able to use the new `pageview` method for this!
```
client.pageview(15, 'http://example.com')
```
